# Auto-generated MCP Server
# Generated by mcpr::mcp_roclet

library(mcpr)

# Tool: create_json_schema
create_json_schema_tool <- new_tool(
  name = "create_json_schema",
  description = "Create a JSON Schema object for MCP tool inputs with property validation",
  input_schema = schema(
    properties = properties(
      properties = property_object("properties", "List of property definitions created with properties()", required = TRUE),
      type = property_string("type", "Type of the schema (default: 'object')", required = TRUE),
      additional_properties = property_boolean("additional_properties", "Whether additional properties are allowed", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: schema
    result <- schema(params$properties, params$type, params$additional_properties)
    response_text(result)
  }
)

# Tool: create_string_property
create_string_property_tool <- new_tool(
  name = "create_string_property",
  description = "Create a string property with validation constraints for MCP schemas",
  input_schema = schema(
    properties = properties(
      title = property_string("title", "Short title for the property", required = TRUE),
      description = property_string("description", "Longer description of the property", required = TRUE),
      required = property_boolean("required", "Whether the property is required", required = TRUE),
      enum = property_array("enum", "Optional character vector of allowed values", required = TRUE),
      pattern = property_string("pattern", "Optional regex pattern the string must match", required = TRUE),
      min_length = property_number("min_length", "Optional minimum length", required = TRUE),
      max_length = property_number("max_length", "Optional maximum length", required = TRUE),
      format = property_enum("format", "Optional format constraint", values = c("date-time", "email", "uri", "hostname", "ipv4", "ipv6"), required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: property_string
    result <- property_string(params$title, params$description, params$required, params$enum, params$pattern, params$min_length, params$max_length, params$format)
    response_text(result)
  }
)

# Tool: create_number_property
create_number_property_tool <- new_tool(
  name = "create_number_property",
  description = "Create a number property with range and type constraints for MCP schemas",
  input_schema = schema(
    properties = properties(
      title = property_string("title", "Short title for the property", required = TRUE),
      description = property_string("description", "Longer description of the property", required = TRUE),
      required = property_boolean("required", "Whether the property is required", required = TRUE),
      minimum = property_number("minimum", "Optional minimum value", required = TRUE),
      maximum = property_number("maximum", "Optional maximum value", required = TRUE),
      exclusive_minimum = property_boolean("exclusive_minimum", "Whether minimum is exclusive", required = TRUE),
      exclusive_maximum = property_boolean("exclusive_maximum", "Whether maximum is exclusive", required = TRUE),
      multiple_of = property_number("multiple_of", "Optional value the number must be a multiple of", required = TRUE),
      integer = property_boolean("integer", "Whether the number should be an integer", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: property_number
    result <- property_number(params$title, params$description, params$required, params$minimum, params$maximum, params$exclusive_minimum, params$exclusive_maximum, params$multiple_of, params$integer)
    response_text(result)
  }
)

# Tool: create_boolean_property
create_boolean_property_tool <- new_tool(
  name = "create_boolean_property",
  description = "Create a boolean property for MCP schemas",
  input_schema = schema(
    properties = properties(
      title = property_string("title", "Short title for the property", required = TRUE),
      description = property_string("description", "Longer description of the property", required = TRUE),
      required = property_boolean("required", "Whether the property is required", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: property_boolean
    result <- property_boolean(params$title, params$description, params$required)
    response_text(result)
  }
)

# Tool: create_enum_property
create_enum_property_tool <- new_tool(
  name = "create_enum_property",
  description = "Create an enum property with predefined values for MCP schemas",
  input_schema = schema(
    properties = properties(
      title = property_string("title", "Short title for the property", required = TRUE),
      description = property_string("description", "Longer description of the property", required = TRUE),
      values = property_array("values", "Character vector of allowed values", required = TRUE),
      required = property_boolean("required", "Whether the property is required", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: property_enum
    result <- property_enum(params$title, params$description, params$values, params$required)
    response_text(result)
  }
)

# Tool: start_mcp_server_io
start_mcp_server_io_tool <- new_tool(
  name = "start_mcp_server_io",
  description = "Start an MCP server using stdin/stdout transport",
  input_schema = schema(
    properties = properties(
      mcp = property_object("mcp", "An MCP server object created with new_server()", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: serve_io
    result <- serve_io(params$mcp)
    response_text(result)
  }
)

# Tool: create_mcp_server
create_mcp_server_tool <- new_tool(
  name = "create_mcp_server",
  description = "Create a new MCP server with specified name, description, and version",
  input_schema = schema(
    properties = properties(
      name = property_string("name", "Name of the MCP server", required = TRUE),
      description = property_string("description", "Description of the MCP server", required = TRUE),
      version = property_string("version", "Version of the MCP server", required = TRUE),
      tools = property_array("tools", "List of tools (optional)", required = TRUE),
      resources = property_array("resources", "List of resources (optional)", required = TRUE),
      prompts = property_array("prompts", "List of prompts (optional)", required = TRUE),
      ... = property_string("...", "Forwarded to [new_server()]", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: new_server
    result <- new_server(params$name, params$description, params$version, params$tools, params$resources, params$prompts, params$...)
    response_text(result)
  }
)

# Tool: create_mcp_tool
create_mcp_tool_tool <- new_tool(
  name = "create_mcp_tool",
  description = "Create a new MCP tool with input schema and handler function",
  input_schema = schema(
    properties = properties(
      name = property_string("name", "Name of the tool", required = TRUE),
      description = property_string("description", "Description of the tool", required = TRUE),
      input_schema = property_object("input_schema", "Input schema for the tool (must be a schema object)", required = TRUE),
      handler = property_object("handler", "Function to handle the tool execution", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: new_tool
    result <- new_tool(params$name, params$description, params$input_schema, params$handler)
    response_text(result)
  }
)

# Tool: create_mcp_resource
create_mcp_resource_tool <- new_tool(
  name = "create_mcp_resource",
  description = "Create a new MCP resource with URI and MIME type",
  input_schema = schema(
    properties = properties(
      name = property_string("name", "Name of the resource", required = TRUE),
      description = property_string("description", "Description of the resource", required = TRUE),
      uri = property_string("uri", "URI of the resource", required = TRUE),
      mime_type = property_string("mime_type", "MIME type of the resource (optional)", required = TRUE),
      handler = property_object("handler", "Function to handle the resource request", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: new_resource
    result <- new_resource(params$name, params$description, params$uri, params$mime_type, params$handler)
    response_text(result)
  }
)

# Tool: create_mcp_prompt
create_mcp_prompt_tool <- new_tool(
  name = "create_mcp_prompt",
  description = "Create a new MCP prompt with arguments and handler function",
  input_schema = schema(
    properties = properties(
      name = property_string("name", "Name of the prompt", required = TRUE),
      description = property_string("description", "Description of the prompt", required = TRUE),
      arguments = property_array("arguments", "List of arguments for the prompt", required = TRUE),
      handler = property_object("handler", "Function to handle the prompt execution", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: new_prompt
    result <- new_prompt(params$name, params$description, params$arguments, params$handler)
    response_text(result)
  }
)

# Tool: add_mcp_capability
add_mcp_capability_tool <- new_tool(
  name = "add_mcp_capability",
  description = "Add a tool, resource, or prompt capability to an existing MCP server",
  input_schema = schema(
    properties = properties(
      mcp = property_object("mcp", "An MCP server object", required = TRUE),
      capability = property_object("capability", "A tool, resource, or prompt capability object", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: add_capability
    result <- add_capability(params$mcp, params$capability)
    response_text(result)
  }
)

# Tool: create_text_response
create_text_response_tool <- new_tool(
  name = "create_text_response",
  description = "Create a text response for MCP tool handlers",
  input_schema = schema(
    properties = properties(
      text = property_string("text", "Text content for the response", required = TRUE),
      image = property_string("image", "Image content", required = TRUE),
      audio = property_string("audio", "Audio content", required = TRUE),
      video = property_string("video", "Video content", required = TRUE),
      file = property_string("file", "File content", required = TRUE),
      type = property_string("type", "Type of the content", required = TRUE),
      resource = property_string("resource", "Resource content", required = TRUE),
      is_error = property_string("is_error", "Whether the response is an error", required = TRUE),
      mime_type = property_string("mime_type", "Mime type of the content", required = TRUE),
      ... = property_string("...", "Mutliple `response` objects", required = TRUE)
    )
  ),
  handler = function(params) {
    # Call the original function: response_text
    result <- response_text(params$text, params$image, params$audio, params$video, params$file, params$type, params$resource, params$is_error, params$mime_type, params$...)
    response_text(result)
  }
)


# Create MCP server
mcp_server <- new_server(
  name = "Auto-generated MCP Server",
  description = "MCP server generated from R functions with @mcp tags",
  version = "1.0.0"
)

mcp_server <- add_capability(mcp_server, create_json_schema_tool)
mcp_server <- add_capability(mcp_server, create_string_property_tool)
mcp_server <- add_capability(mcp_server, create_number_property_tool)
mcp_server <- add_capability(mcp_server, create_boolean_property_tool)
mcp_server <- add_capability(mcp_server, create_enum_property_tool)
mcp_server <- add_capability(mcp_server, start_mcp_server_io_tool)
mcp_server <- add_capability(mcp_server, create_mcp_server_tool)
mcp_server <- add_capability(mcp_server, create_mcp_tool_tool)
mcp_server <- add_capability(mcp_server, create_mcp_resource_tool)
mcp_server <- add_capability(mcp_server, create_mcp_prompt_tool)
mcp_server <- add_capability(mcp_server, add_mcp_capability_tool)
mcp_server <- add_capability(mcp_server, create_text_response_tool)

# Start the server
serve_io(mcp_server)
